# Generated by Django 4.1.4 on 2023-05-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ioecropedquestionpaper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ioecropedquestionpaper',
            new_name='ioequestionpaper',
        ),
    ]
